# Generated by Django 4.0.5 on 2022-06-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Mn', 'Management'), ('TP', 'Transportion'), ('LG', 'Logistics'), ('MK', 'Marketing'), ('SV', 'Service'), ('FN', 'Finance')], max_length=2, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['name', 'description', 'start_date', 'end_date', 'event'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('Mn', 'Management'), ('TP', 'Transportion'), ('LG', 'Logistics'), ('MK', 'Marketing'), ('SV', 'Service'), ('FN', 'Finance')], max_length=2, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('national_registration_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('GN', 'Prefer not to say')], max_length=6)),
                ('employment_status', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time')], max_length=2)),
                ('role', models.CharField(choices=[('MG', 'Manager'), ('JM', 'Junior Manager'), ('OS', 'Ordinary staff')], max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['full_name', 'phone', 'email', 'national_registration_number', 'date_of_birth', 'gender', 'address', 'department', 'employment_status', 'role'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('event_type', models.CharField(choices=[('AN', 'Anniversary'), ('WD', 'Wedding'), ('FN', 'Funeral'), ('BD', 'Birthday'), ('CO', 'Coporate'), ('GT', 'Get-together')], max_length=2)),
                ('contract_sum', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('ordinary_guests', models.IntegerField()),
                ('vip_guests', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.client')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['name', 'start_date', 'end_date', 'description', 'event_type', 'city', 'province', 'country', 'client', 'contract_sum', 'budget', 'actual', 'ordinary_guests', 'vip_guests'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=600)),
                ('type', models.CharField(choices=[('MX', 'Mixed'), ('MT', 'Meaty'), ('VG', 'Vegeterian'), ('ST', 'Starchy')], max_length=2)),
                ('country_of_origin', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Peformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Mn', 'Management'), ('TP', 'Transportion'), ('LG', 'Logistics'), ('MK', 'Marketing'), ('SV', 'Service'), ('FN', 'Finance')], max_length=2, null=True)),
                ('salary', models.IntegerField()),
                ('date', models.DateField()),
                ('peformance', models.CharField(choices=[('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('CI', 'Below Average')], max_length=2)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.employee')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.event')),
            ],
            options={
                'verbose_name_plural': 'Human Resource',
                'ordering': ['employee', 'department', 'event', 'salary', 'peformance', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('allergins', models.CharField(max_length=200)),
                ('unit_serving', models.IntegerField()),
                ('menu', models.ManyToManyField(to='cccdata.menu')),
                ('partner', models.ManyToManyField(to='cccdata.partner')),
            ],
            options={
                'verbose_name_plural': 'Menu Items',
                'ordering': ['name', 'allergins', 'unit_serving'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('EQ', 'Equipment'), ('MT', 'Material'), ('PS', 'Perishables')], max_length=2)),
                ('unit', models.CharField(max_length=30)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date_proccured', models.DateField()),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.supplier')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'ordering': ['name', 'type', 'unit_price', 'quantity', 'supplier', 'date_proccured'],
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=30)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('profit_per_serving', models.IntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.item')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.supplier')),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
                'ordering': ['name', 'brand', 'supplier', 'item', 'unit_price', 'profit_per_serving', 'quantity'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Mn', 'Management'), ('TP', 'Transportion'), ('LG', 'Logistics'), ('MK', 'Marketing'), ('SV', 'Service'), ('FN', 'Finance')], max_length=2, null=True)),
                ('name', models.CharField(max_length=200)),
                ('expense_type', models.CharField(choices=[('EO', 'Extra Over'), ('AC', 'Accomodation'), ('CA', 'Communication/Airtime'), ('KT', 'Kitchen'), ('ME', 'Materials and Equipment'), ('FI', 'Food Items'), ('DM', 'Damages'), ('VM', 'Vehicle repair and Maintenance'), ('GS', 'Gas'), ('UN', 'Uniform')], max_length=2)),
                ('description', models.CharField(max_length=1000)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('order_status', models.CharField(choices=[('PC', 'Purchased'), ('RT', 'Rented')], max_length=2)),
                ('payment_method', models.CharField(choices=[('CS', 'Cash'), ('CR', 'Card'), ('CD', 'Credit'), ('AM', 'Airtel Money'), ('MM', 'MTN Money'), ('OT', 'Other')], max_length=2)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.activity')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.event')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.supplier')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'ordering': ['name', 'description', 'supplier', 'department', 'activity', 'date', 'unit_price', 'quantity', 'order_status', 'payment_method'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.event'),
        ),
    ]
