# Generated by Django 4.0.5 on 2022-06-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cccdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name', 'phone', 'email', 'national_registration_number', 'date_of_birth', 'gender', 'address', 'department', 'employment_status', 'role'], 'verbose_name_plural': 'Employyes'},
        ),
    ]
