# Generated by Django 4.0.5 on 2022-06-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cccdata', '0007_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('MG', 'Manager'), ('JM', 'Junior Manager'), ('OS', 'Ordinary staff'), ('DR', 'Director')], max_length=2, null=True),
        ),
    ]
