# Generated by Django 4.0.5 on 2022-06-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cccdata', '0008_alter_employee_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peformance',
            options={'verbose_name_plural': 'Staff Peformance'},
        ),
    ]
