# Generated by Django 4.0.5 on 2022-06-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cccdata', '0010_remove_item_menu_activity_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.employee'),
        ),
    ]
