# Generated by Django 4.0.5 on 2022-06-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cccdata', '0011_activity_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='partner',
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cccdata.menu'),
        ),
    ]
