# Generated by Django 4.0.5 on 2022-06-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cccdata', '0012_remove_item_partner_item_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('MG', 'Manager'), ('JM', 'Junior Manager'), ('OS', 'Staff'), ('DR', 'Director')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_proccured',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='allergins',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='country_of_origin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='peformance',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
