# Generated by Django 4.0.5 on 2022-06-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cccdata', '0015_alter_expenses_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('EO', 'Extra Over'), ('AC', 'Accomodation'), ('CA', 'Communication/Airtime'), ('KT', 'Kitchen'), ('ME', 'Materials and Equipment'), ('FI', 'Food Items'), ('DM', 'Damages'), ('VM', 'Vehicle repair and Maintenance'), ('GS', 'Gas'), ('LB', 'Labor'), ('TX', 'Tax'), ('UN', 'Uniform')], max_length=2),
        ),
    ]
