# Generated by Django 4.0.5 on 2022-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cccdata', '0024_alter_ingredients_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='actual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract_sum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='profit_per_serving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='peformance',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
