# Generated by Django 4.0.5 on 2022-06-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cccdata', '0025_alter_employee_date_of_birth_alter_event_actual_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Expenses',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, default='YYYY-MM-DD', null=True),
        ),
    ]
